#Manual to start the container:
#Go to the terminal on the folder where the docker-compose.yml is, and run the command:
#docker-compose up -d

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: my-rabbit
    ports:
      - "8080:15672"    # Interface web (GUI) → http://localhost:8090
      - "5672:5672"     # Porta de conexão padrão (apps)
      - "25676:25676"   # Para clustering (opcional)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
